composer.json

Looking at http://mpdf1.com/manual/index.php?tid=265 and http://www.mpdf1.com/mpdf/index.php?page=Licence there is no option to use 'any later version' of the GPL so it looks like the code is GPL 2 only.
Support details are added for convenience.

mPDF is GPL 2 only, add support details to composer.json

---

mpdf.php

Currently, the LEDGER and TABLOID sizes are specified in millimeters while others are specified in points. This PR changes the sizes for LEDGER and TABLOID to be specified in points as well.
Reference:
http://www.gnu.org/software/gv/manual/html_node/Paper-Keywords-and-paper-size-in-points.html

Fix LEDGER and TABLOID

---

includes/functions.php

Removing array_insert(), as it is unused in this library. Additionally, it is not name spaced and is not prefixed (and is therefore causing conflicts with another package).

Remove unused array_insert()

---

src/DirectWrite.php
src/Mpdf.php

The variable `$fill` was always undefined (see [e8dcfd34])
DirectWrite::Write now has a new parameter `$fill`, analogous to other
functions.
`Mpdf::Write` (which delegates to `DirectWrite::Write`) has the same.

Bugfix: undefined variable in DirectWrite::Write

---

src/Image/Svg.php

Environment: 
PHP 7.1
mPDF 7.0
I've undefined index error when I include svg image like this:
```
<svg version="1.1"
style="font-family: 'lucida grande', 'lucida sans unicode', arial, helvetica, sans-serif; font-size: 12px;"
xmlns="http://www.w3.org/2000/svg" width="600" height="400">
<desc>Created with Highcharts 4.2.7</desc>
<defs>
<rect x="0" y="0" width="551" height="246"></rect>
</defs>
<rect x="0" y="0" width="600" height="400" fill="#FFFFFF"
class=" highcharts-background"></rect>
<g class="highcharts-grid"></g>
<g class="highcharts-grid"></g>
<g class="highcharts-axis">
<path fill="none" d="M 91.5 318 L 91.5 328" stroke="#C0D0E0"
stroke-width="1" opacity="1"></path>
<path fill="none" d="M 189.5 318 L 189.5 328" stroke="#C0D0E0"
stroke-width="1" opacity="1"></path>
<path fill="none" …
```

Fix svg parsing

---

src/Mpdf.php
tests/Mpdf/FpdiTest.php

This method is needed to support importing of PDF documents with FPDI
which uses escaped sequences in string values if the resulting document
should be encrypted.
See https://stackoverflow.com/questions/45052154/pdf-manipulation-images-are-distorted-after-few-consecutive-operations-on-pdf for details.

Added _unescape() method

---

src/Mpdf.php
src/functions.php
tests/Issues/Issue491Test.php

In germany we use comma as decimal point and dot as thousands separator.  `floatval()` is not locale aware (as is `scanf()`), so we must use `str_replace()` magic :wink:

fixed colsum float calculation for german based locales

---

src/Language/LanguageToFont.php
src/Language/ScriptToLanguage.php

- Use single quotes instead of double quotes
- Use static properties for heavy declarations
- Remove unnecessary regex for splitting
- Use !empty($foo) instead of isset($foo) && $foo
- Strict type checking for comparisons
- Refactor ifs to shorten them
(Replaces #544)

Language code cleanup

---

src/Conversion/DecToAlpha.php
src/Conversion/DecToCjk.php
src/Conversion/DecToHebrew.php
src/Conversion/DecToOther.php
src/Conversion/DecToRoman.php

- Optimisation: Use (int) instead of intval()
- Optimisation: Don't use count() or strlen() in `for` condition
- Optimisation: Use ** (>= 5.6) instead of `pow()`
- Use strict comparison (===) where needed
- Some code readability changes ($c1 initialized with default value, default property value in declaration)
Replaces #543

Conversion code cleanup

---

composer.json

Tried to install in a Laravel 5.2 application and ran into some issues with conflicting versions of random compat.  This PR allows for both 1.x/2.x versions to co-exist.  See https://github.com/paragonie/random_compat/commit/856e858ab44b76ae67d8f8398d496a7464ac4656

Fix for version conflicts of paragonie/random_compat

---

src/Color/ColorConverter.php

* Remove unnecessary parentheses
* Use single quotes
* Use short syntax
* Strict comparison for strings
* Clean up ifs
* Add missing phpdoc annotations

Colorconverter cleanup

---

src/Tag.php

Fix two places where code2utf was called without it's Class appended. This was causing some renders to break.

Appended missing Class for static method in Tag.php

---

src/CssManager.php

Replace preg_replace with str_replace to save memory  …
The previous solution used a lot if memory especially when handling (extremely) large CSS input.
I’ve used a patched version with str_replace for several years in my dokuwiki plugin (using ad-hoc function replacement) - but since mpdf is on github now, it is time to create a pull request.
The tests ran OK, but I have no idea how to sufficiently test the code.
See https://github.com/i-net-software/dokuwiki-plugin-siteexport/commit/7181180dce7fe3c0813ea41b412f45fd461096af for my previous solution

 Replace preg_replace with str_replace to save memory

---

src/Tag/BlockTag.php

Missed this one while refactoring.

Import UtfString in \Mpdf\Tag\BlockTag

---

src/Mpdf.php

This PR adds the filename and the line where the header output started

Improve error message if headers already sent

---

src/Cache.php
tests/Mpdf/CacheTest.php

Follow-up for #534. Due to directory permissions issue, it is currently impossible to generate a PDF using one font, then generate another one using a different font and running under a different user (i.e. create a PDF with "font1" from the command line, then another PDF with "font2" from a web server), because the latter cannot write to `tmp/ttfontdata` directory, whenever `umask() !== 0` ― which is usually the case.
**Issue:**
`Mpdf\Cache` uses `mkdir()` to create missing temporary directories.
`mkdir()` takes umask into account (see [PHP documentation](http://php.net/mkdir#refsect1-function.mkdir-parameters)). It's not unusual to have `0002` or `0022` umask by default, so the directories end up not being world-writeable (i.e. having file mode `0775` or `0755` instead of `0777`).
This …

Fix handling permissions on temporary directories

---

src/Mpdf.php
tests/Issues/Issue641Test.php

If trying to insert a TOC, a number of PHP notices in PHP 7.2 are triggered inside `Mpdf::MovePages()` due to `count()` checks on variables that haven't been defined yet.
```
$mpdf = new \Mpdf\Mpdf();
$mpdf->h2toc = array('H1' => 0, 'H2' => 1);
$mpdf->WriteHTML('
Test
<tocpagebreak paging="on" links="on" />
<h1>Heading 1</h1>
<h2>Heading 2</h2>
<h2>Heading 2</h2>
<h2>Heading 2</h2>
<pagebreak/>
<h1>Heading 1</h1>
');
$mpdf->Output();
```

Fix count() must be array PHP Notice

---

src/Mpdf.php
tests/Issues/Issue645Test.php

This issue is most prominent with the `<pagebreak/>` tag, but does effect all other control tags when no attributes are used (i.e `<pagebreak orientation="L"/>` isn't effected, but `<tocpagebreak/>` is).
Resolves #645

Ensure self-closing tags with no attributes are processed when no space between tag and slash

---

src/Mpdf.php
tests/Issues/Issue640Test.php

```
$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML('
<style>
@page {
footer: html_myFooter1;
margin-footer: 0;
}
#bottom {
height: 25mm;
background:red;
}
</style>
<htmlpagefooter name="myFooter1">
<div id="bottom">test</div>
</htmlpagefooter>
');
```
Before the PR, the footer would be set to 0.1mm from the bottom of the page to prevent a division by zero. However, this would leave a noticeable small white line. This PR will push the footer down below the page edge by 0.01 instead.

Fix 0.1mm whitespace when using footer with zero margins

---

src/Mpdf.php
tests/Mpdf/GetFullPathTest.php

This patch resolves an edge-case bug when the `Mpdf::basepathIsLocal` setting hasn't been correctly determined and is set to `false` and assets are trying to load using the absolute path.
Prior to this patch, when `basepathIsLocal` is determined to be `false` (whether that be incorrectly determined due to server configuration, user error, or some other reason) and you are using the absolute path to the asset, it would be convert to a URI in `Mpdf::GetFullPath` and then a HTTP request is triggered in `ImageProcessor::getImage`. This patch helps prevent that HTTP request.
```
$mpdf = new \Mpdf\Mpdf();
$mpdf->basepathIsLocal = false; //manually set for purposes of replication
$mpdf->WriteHTML('<img src="'. __DIR__ . '/assets/Desert.jpg">');
$mpdf->Output();
```
Before the patch, the above …

Ensure $mpdf->GetFullPath uses the absolute path, when able.

---

src/Language/LanguageToFont.php
tests/Mpdf/Language/LanguageToFontTest.php
tests/Mpdf/Language/LanguageToFontTestImplimentation.php

During testing, it was found the `$country` parameter was being lowercased and the IF statements included weren't valid, as they included the country codes in uppercase.
The `fontByScript` method was also set to a protected function. This allows developers greater control over the fonts when extending the `LanguageToFont` class. By making this change, developers don't have to copy the entire `fontByScript` function to their new class. They can instead do:
```php
<?php
class CustomLanguageToFontImplementation extends \Mpdf\Language\LanguageToFont
{
protected function fontByScript($script, $adobeCJK)
{
if ($script === 'latn') {
return 'freeserif';
}
return parent::fontByScript($script, $adobeCJK);
}
}
```
This change goes hand-in-hand with https://github.com/mpdf/mpdf.github.io/pull/81 and …

Write Unit Tests for LanguageToFont Class

---

src/Tag/BlockTag.php
tests/Issues/Issue730Test.php

The return value of `$currblk['padding_left']` can be an integer or a float. Since `is_int` only checks for integers the values that were floats were getting set to 0. Changing it to `is_numeric` covers both integers and floats and brings it inline with the type checking done on lines 739 and 740 of the same file.
Resolves #730

Fix incorrect left padding issue on tag following float

---

src/TableOfContents.php
tests/Mpdf/TocNumbering.php

The 'suppress' setting is [meant for suppressing the page numbering on individual pages](http://mpdf.github.io/reference/mpdf-functions/addpagebyarray.html) and shouldn't apply to the TOC when showing page numbers. This PR ensures the 'suppress' setting is disabled when rendering the TOC. 
Resolves #777

Ensure TOC Numbering is shown even when the 'suppress' setting is enabled

---

src/Image/Svg.php

Split attribute values by comma, comma + whitespace or whitespace,  instead comma and whitespace in same time

Fix for notices on line 1477 in Image/Svg.php

---

src/Form.php
tests/Issues/Issue897.php

The non-active checkbox field is more difficult to control via CSS due to it making use of two colours: a white square and a black cross. Because of this, I've only focused on the radio field.

Allow the non-active form radio field color to be set with CSS

---

src/HTMLParserMode.php
src/Mpdf.php
tests/Mpdf/WriteHtmlTest.php

Hey! Thanks for this package, it works quite well.
I was pleased to see that `Destination::FILE` constants exist but was disappointed to see the same didn't exist for the magic numbers which defined the second argument to `WriteHTML()`
I specifically referred to the [external documentation](https://mpdf.github.io/reference/mpdf-functions/writehtml.html#parameters) while doing this as well:
* rename `$sub` to `$mode`, I don't know what sub was meant to mean but I don't see why it shouldn't be called `$mode`
* replace any checks that relied on the order of the constants (ie `$sub < 1) with their true meanings to aid readability
* enforced strict equality checks `===` and enforced that the mode should be one of the permitted modes
* I named the constants the best I could think of but more …

chore(WriteHTML): Make WriteHTML use const instead of magic numbers

---

src/Config/ConfigVariables.php
src/Mpdf.php
src/RemoteContentFetcher.php

Set your own CA certificate store for SSL Certificate verification when using cURL. This is useful setting to use on hosts with outdated CA certificates.

Allow custom cURL CA certificate

---

src/RemoteContentFetcher.php

This makes it easier to debug problems with external resources

Log cURL error when it occurs

---

src/Mpdf.php
src/Tag/Img.php
src/Tag/Input.php
src/Tag/Meter.php

Any size conversion related to images should [use the img_dpi setting](https://mpdf.github.io/reference/mpdf-variables/img-dpi.html) instead of [dpi](https://mpdf.github.io/reference/mpdf-variables/dpi.html).

Use the img_dpi setting for all images

---

src/Fonts/FontCache.php
src/Fonts/MetricsGenerator.php
src/Mpdf.php
src/Otl.php
src/TTFontFile.php
src/Writer/FontWriter.php
tests/Mpdf/AddFontTest.php
tests/Mpdf/Fonts/FontCacheTest.php
tests/Mpdf/Fonts/MetricsGeneratorTest.php
utils/font_dump.php

This PR standardised the font cache. Instead of crudely generating PHP files with font data, it stores the information in JSON files. 
JSON cache files has a number of benefits:
1. The code to generate the files is much smaller. 
1. The data doesn't need to be escaped
1. It is easier to test and modify
1. More compatible on shared hosting with security that limit the dynamic creation of PHP files
**Backwards Compatibility**
This is fully backwards compatible. There is a one-time font cache refresh to generate the new JSON files, then it's business as usual. The font cache doesn't need flushing before hand.
I tested this PR against the Mpdf Example folder and found no visual regressions. 
**Benchmarks**
By forgoing the PHP cache, we lose OPCaching on these files, but I've kept the JSON …

Convert Font Cache from PHP to JSON Files

---

src/Image/ImageProcessor.php
tests/Mpdf/Image/ImageProcessorTest.php

Only allow HTTP, HTTPS and File streams
Resolves #949

Prevents PHAR wrapper security issue when loading images

---

src/Mpdf.php

Fix issue introduced in https://github.com/mpdf/mpdf/commit/6cb5ddcaed56d0da49dea54d8245b01854f7faab by avoiding setting the cell width to 0 if it was undefined.
Using `null` instead of putting back the `if (isset(..)) { .. }` construct to avoid future confusion.

Fix #860: correctly initialize cell width for nested tables

---

src/FpdiTrait.php
tests/Issues/Issue900Test.php

This PR is a FPDI v2-compatible fix for #900. 
**This applies to external links only**. Internal links will need to be tackled separately on account of the major overhead of tracking which page was imported where, and where the actual internal link should point.
It successfully accounts for imported pages that are offset, or a different size to the original, and accounts for the mPDF page size as well.
Adding this functionality was quite involved and testing is welcome.

Import and display external links on imported PDFs

---

src/Mpdf.php
tests/Issues/Issue1056Test.php

currently it is possible to misuse `COLLATION-GROUP` to `require` arbitrary php files.
This can be dangerous if you accept html from third party.
Just have a look at the test. The current master/development would fail because it cant locate FOOBAR.php.

security, open require in COLLATION-GROUP

---

src/Barcode/EanUpc.php
tests/Mpdf/Barcode/EanUpcTest.php

Because PHP throws warnings if `$code` has non-numeric chars:
```
PHP Warning:  A non-numeric value encountered in /vendor/mpdf/mpdf/src/Barcode/EanUpc.php on line 54
PHP Warning:  A non-numeric value encountered in /vendor/mpdf/mpdf/src/Barcode/EanUpc.php on line 62
```

Valid EAN UPC barcode and throw BarcodeException if is not valid.

---

CHANGELOG.md
src/Writer/MetadataWriter.php
tests/Mpdf/MpdfTest.php

I decided to extend existing `MpdfTest` instead of creating a separate case.
Resolves mpdf#1083

Fix date and time format in the info dictionary

---

src/Mpdf.php

When executed from command line SCRIPT_NAME is missing

Fix missing SCRIPT_NAME

---

CHANGELOG.md
src/Barcode.php
src/Barcode/Code128.php
src/Mpdf.php
src/Tag/BarCode.php
tests/Mpdf/Barcode/Code128Test.php

Added new barcode type C128RAW.
Needed to generate advanced barcodes.
For example: compressed alfa-numeric barcodes with subtype change in middle of barcode
"A1234567890" is possible to code only in 128A or 128B
`<barcode code="A1234567890" type="C128A"/>`
with RAW type we can change the subtype after letter A
`<barcode code="103 33 99 12 34 56 78 90" type="C128RAW"/>`
103 - start 128A
33 - "A"
99 - change to 128C
12 - "12" ...
check digit and stop are added automaticaly by library
same result with ~30% shorter barcode
more info https://en.wikipedia.org/wiki/Code_128

Add new barcode type C128RAW

---

src/Mpdf.php
tests/Issues/Issue1197Test.php

ErrorException Uninitialized string offset: 0
/var/www/project/vendor/mpdf/mpdf/src/Mpdf.php:17947 ***
/var/www/project/vendor/mpdf/mpdf/src/Mpdf.php:17947 Mpdf\Mpdf::setCSS
/var/www/project/vendor/mpdf/mpdf/src/Tag/A.php:36 Mpdf\Tag\A::open
/var/www/project/vendor/mpdf/mpdf/src/Tag.php:243 Mpdf\Tag::OpenTag
/var/www/project/vendor/mpdf/mpdf/src/Mpdf.php:13628 Mpdf\Mpdf::WriteHTML
It used to work silently in the background and change the variable to an array but as of PHP 7.1 it will fail completely.

Fix: Uninitialized string offset: 0

---

CHANGELOG.md
src/Cache.php
src/Fonts/FontCache.php

Two parallel running processes writing the cache run into an error.
1. file_put_contents() is binary-safe and FontCache should use write() from Cache.php
2. file_put_contents() is not atomic. Therefore a different technique should be used. Write temp and then use rename().

Atomic cache writing.

---

src/OtlDump.php

On line 546, a variable $c was missing a $. This results in a undefined constant.

Fix typo in OtlDump.php

---

composer.json

See https://github.com/paragonie/random_compat/compare/v9.99.99...v9.99.100
The `9.99.100` release allow to install on PHP 7 or PHP 8.
Changes in `composer.json` was based on:
```
composer depends paragonie/random_compat
mpdf/mpdf         v8.0.7   requires  paragonie/random_compat (^1.4|^2.0|9.99.99)
symfony/polyfill  v1.18.1  requires  paragonie/random_compat (~1.0|~2.0|~9.99)
```
So `mpdf/mpdf` blocks to update to the latest version.
I think this PR should allow now to it.

Allow paragonie/random_compat higher than 9.99.99

---

CHANGELOG.md
src/Mpdf.php
tests/Mpdf/SubstitutionTest.php

This PR adds the method `Mpdf::aliasReplace($html, $PAGENO, $NbPgGp, $NbPg)` with a simple refactoring for the substitution of `{nb}`, `{nbpg}`, `{PAGENO}` and `{DATE ...}` aliases in the header and footer.
As requested in #172 and #267, the method is applied on all the pages (as suggested by @jochenwezel) thus allowing the use of these aliases in the body of the PDF.

Allows `{nb}`, `{nbpg}` and `{PAGENO}` substitution in body

---

CHANGELOG.md
src/Config/ConfigVariables.php
src/Mpdf.php
src/RemoteContentFetcher.php

As discussed in #1376, this PR adds an undocumented configuration variable `curlExecutionTimeout` that allows a user to set the `CURLOPT_TIMEOUT` option when fetching remote content. Variable name was chosen as to be backwards compatible.

Added curlExecutionTimeout configuration variable

---

CHANGELOG.md
src/Utils/Arrays.php
tests/Issues/Issue538Test.php
tests/Mpdf/Utils/ArraysTest.php

When using more than three classes on an element, not all combinations were generated because of an issue with the combinations function in the Arrays helper class.
e.g. when generating the combinations for 'a', 'b', 'c' and 'd' (with k=2) the combination generating algorithm would correctly generate `ab`,` ac`,`ad` and then jump to `bd` and `cd` instead of generating `bc` as well, because it only increased the middle index, without resetting the last index first: `[0, 3]` became `[1, 3]` instead of `[1, 2]`.

Fix compound classes support when combining more than three classes

---

CHANGELOG.md
src/CssManager.php
src/ServiceFactory.php

The `CssManager` class didn't make use of the `RemoteContentFetcher` class, meaning that when it tried to fetch data via `curl`, it wouldn't all the options that the `RemoteContentFetcher` was able to use.

Update CssManager to use RemoteContentFetcher

---

CHANGELOG.md
src/Color/ColorConverter.php
tests/Mpdf/Color/ColorConverterTest.php

This pull request resolves an issue with newer php versions printing a deprecation message (`Invalid characters passed for attempted conversion, these have been ignored`) when trying to decode invalid hex characters using the [hexdec](https://www.php.net/manual/function.hexdec.php) method.
The passed string is now validated to only contain hexadecimal characters before it gets passed to [hexdec](https://www.php.net/manual/function.hexdec.php) using [ctype_xdigit](https://www.php.net/manual/function.ctype-xdigit.php). If the passed string does not contain only hex chars the method returns `0` just as php does.

Ensure that all digits of a string are hexadecimal before decoding

---

CHANGELOG.md
src/TTFontFile.php

Fix for #1504 
Added the ability to check the fread result to overcome the 8192 bytes limit in compressed / buffered streams.

overcome fread limit in buffered streams (e.g. phar) (Closes #1504)

---

CHANGELOG.md
src/Hyphenator.php
tests/Mpdf/HyphenatorTest.php

Hi,
currently only URLs starting with `http:` or `www.` are prevented from hyphenation. I have added `https:` to the regex to include URLs starting with https.
Best, Hannes

Prevent hyphenation of urls starting with https and E-Mail addresses

---

CHANGELOG.md
src/Form.php
src/Tag/Input.php
src/Tag/TextArea.php
tests/Issues/Issue834Test.php

Solves issue https://github.com/mpdf/mpdf/issues/834
According to [this commit](https://github.com/foliojs/pdfkit/commit/131df9e0ae4bb7db8d3328a745a9acecdf74a311), it seems to be completely enough to just set the font-size parameter within the AcroForm definition to 0.

Enable auto font-size for active forms

---

src/Mpdf.php
tests/Mpdf/AdjustHtmlTest.php
tests/data/html/long-string-with-kwt-match.html
tests/data/html/long-string-without-kwt-match.html

This PR optimises the Keep With Tables `preg_replace` in the `Mpdf::AdjustHTML()` method so that:
1. It only runs when the `use_kwt` configuration option is enabled
2. The regex match statement has been modified to prevent lookbacks in PCRE
3. Errors will cause the statement to be ignored altogether
**The Problem**
In PHP runtimes with PCRE JIT enabled, larger blocks of HTML could trigger a PCRE_ERROR_JIT_STACKLIMIT error if the pattern `<h1></h1><table></table>` isn't in the HTML (it can still happen even if they are; but it'll depend on the length of HTML and the location of the pattern as to how many steps PCRE takes). This would result in `preg_replace()` returning `null` and the generated PDF would be blank (see https://stackoverflow.com/a/39688067).
An example of the inefficiencies …

Resolve PCRE JIT Stack Limit Error

---

CHANGELOG.md
src/Config/ConfigVariables.php

Recently I started getting reports about HTTP(S) images not being loaded in PDFs from SiteGround hosted websites. The investigation into this revealed that SiteGround's anti-bot system is now blocking requests with old user agents because they are considered suspicious.
Information from SiteGround:
> "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:13.0) Gecko/20100101 Firefox/13.0.1"
> As you can see, it is using a quite old Firefox version (released in June 5, 2012) which is considered as suspicious and blocked by our anti-bot system. We recently started blocking such requests which originate from User Agents with quite old browser versions as in most cases these are malicious.
The recommended solution is to update the user agent to the current version of Firefox.
I haven't added any unit …

Update default user agent used for cURL requests

---

composer.json

This dep is unused and it's also deprecated, let's not force-installing.

Remove php-http/message-factory from deps

---

CHANGELOG.md
composer.json
phpunit.xml
src/AssetFetcher.php
src/Http/CurlHttpClient.php
src/Http/SocketHttpClient.php
src/Image/ImageProcessor.php
src/Mpdf.php
src/SizeConverter.php
src/Writer/MetadataWriter.php
src/Writer/ResourceWriter.php
tests/Mpdf/TestLogger.php
tests/Mpdf/psr-log-2/TestLogger.php
tests/Mpdf/psr-log-3/TestLogger.php

Hi @finwe! 👋🏻 
I have seen some of the other [PRs related to adding `psr/log` v3 support](https://github.com/mpdf/mpdf/pull/1856). I understand you do not want to drop v2 support just to achieve compatibility with v3. @greg-1-anderson gave us the idea to try to achieve compatibility with both through the use of a trait. Thanks Greg!
This proposal shows how we might support `psr/log` v2 and v3 without having to support two different releases in *this* codebase.
In a separate [package](https://github.com/ChromaticHQ/psr-log-aware-trait):
* We created a trait to handle LoggerAwareInterface's `setLogger()` implementation. We implemented support for both psr/log [v2](https://github.com/ChromaticHQ/psr-log-aware-trait/blob/2.x/src/PsrLogAwareTrait.php) and …

Proof of Concept: psr/log v2 & v3 Support

---

src/Image/ImageProcessor.php
tests/Issues/Issue1928Test.php

In order to fix https://github.com/mpdf/mpdf/issues/1928 I've refactored the ImageProcessor -> processPng function and replaced strpos function by getting chunk types from chunk bytes 5-8.
I've refactored all places and not only the gAMA section which was mentioned in the issue

Fix broken PNG due to incorrect chunk type detection #1928

---

.github/workflows/tests.yml
CHANGELOG.md
README.md
composer.json

Hey there :wave: 
I saw that there were already some issues tackled regarding PHP 8.3 compatibility and I wondered, why mpdf was not marked as compatible yet :slightly_smiling_face: 
If I missed something, please let me know. Otherwise it would be nice, if we could get a release, that is compatible with PHP 8.3 :rocket:

feat: Add PHP 8.3 compatibility

---

src/Tag/Option.php
tests/Issues/Issue1934Test.php

Fixing an issue of the "Undefined array key "VALUE" notice in Option.php.
Link to the reported issue: https://app.glitchtip.com/evoludata/issues/2379545

Fix Warning Undefined array key "VALUE" in Option.php

---

CHANGELOG.md
src/Mpdf.php
src/Tag/BlockTag.php
src/Tag/Tr.php
tests/Issues/Issue2004Test.php
tests/Mpdf/MpdfTest.php

This code is sponsored by Launix (https://launix.de) and released under GPL 2.0
In order to not get into fork hell, we appreciate a fast release of the feature in the next minor version.

Add support for page-break-before: avoid; and page-break-after: avoid; for <tr> elements

---

src/Mpdf.php
tests/Issues/Issue2013Test.php

When a block with `page-break: avoid;` is too large to fit on a single page, mPDF used to paginate it one line per page, which is unwanted. This change detects unavoidable oversized “avoid” blocks and forces a break exactly at the page boundary to produce sensible pagination.
- Adjust pagination to split oversized avoid blocks at page limits
- Add unit test covering the oversized avoid-block scenario
Note: Merge/revert noise has been squashed; no net change for the earlier Outlook blockquote styling experiment (added then reverted).

Fix page-break: avoid for oversized blocks by splitting at page limit

---

src/SizeConverter.php
tests/Issues/Issue2051Test.php

A famous email client creates quotations with `<blockquote style="width: 100%%">`. This is faulty CSS however all browsers I tested interpreted %% as % but not as px. Mpdf however defaults to "px" interpretation which leads to 100px wide blockquotes which in consequence creates PDF documents with a very small stripe of text, lots of line breaks and a large number of pages.
So we should mimic the browser's behaviour and interpret CSS measurements with %% as unit as percent rather than pixels.

Be more graceful with faulty HTML (created from famous email clients) which are interpreted by all browsers gracefully, too
