mpdf/mpdf

- .gitattributes
- README.md
- README.txt
Just adding a gitattributes file to help CRLF issues and a pretty README.
> Janitorial fixes for GitHub

- src/Mpdf.php
- tests/Issues/Issue457Test.php
- tests/data/pdfs/2-Page-PDF_1_3.pdf
Pull request for issue #457 
Please verify, that I understood the code correct:
I assumed that -$tpl['box']['y'] means -1 *$tpl['box']['y']
Is this correct?
Like other forks, I used floatval() to solve the problem.
> Issue #457 Fix for Warning: A non-numeric value encountered

- CHANGELOG.md
improve layouting of changelog
> improve layouting

- src/Ucdn.php
Fix undefined constants and the if
> fix constants calls

- src/Image/ImageTypeGuesser.php
- Strict comparisons
- Clean up ifs
> Image type guesser code cleanup

- src/Color/ColorModeConverter.php
* Remove unnecessary parentheses
* Remove unnecessary semicolon
* Use increment/decrement operator
* Use (int) instead of intval()
* Don't use else for last statement
> Colormode converter cleanup

- src/Mpdf.php
> Fix undefined variable rotate

- src/Mpdf.php
- tests/Issues/Issue637Test.php
> Fix PHP notice when using enableImports without importing a PDF

- src/Utils/NumericString.php
- src/Utils/UtfString.php
Some small optimisations & enhanced code readability
> Cleanup src/utils

- src/Config/ConfigVariables.php
- src/Mpdf.php
> Remove legacy showStats configuration option

- src/CssManager.php
- tests/Issues/Issue660Test.php
> Make temporary filename all lowercase to prevent case-sensitive OS problems

- src/Mpdf.php
- tests/Issues/Issue677Test.php
> Prevent PHP Notices caused by footer with a fixed height

- src/Config/FontVariables.php
See https://github.com/mpdf/mpdf/issues/676#issuecomment-385223529
> Include Sun-Exta in the backupSubsFont list

- src/Mpdf.php
- tests/Issues/Issue736Test.php
Resolves https://github.com/mpdf/mpdf/issues/736
> Fix String Offset PHP Notice for Unicode Characters

- src/TableOfContents.php
- tests/Mpdf/TocNumbering.php
> Fix the TOC Numbering when the TOC Page Has a Custom Page Number Format

- src/Mpdf.php
> Throw an explanatory exception on mismatching in_charset and input charset (Closes #861)

- src/Mpdf.php
- tests/Issues/Issue890Test.php
> If the font cache file does not exist, try load it after generating the cache

- src/Otl.php
- tests/Issues/Issue905Test.php
> Fix undefined offset PHP Notice in bidiReorder

- src/Otl.php
- tests/Issues/Issue879Test.php
> Undefined index: diid in src/Otl.php:5383

- tests/Issues/Issue442Test.php
- tests/Issues/Issue645Test.php
- tests/Mpdf/Barcode/ImbTest.php
- tests/Mpdf/Barcode/Rm4SccTest.php
- tests/Mpdf/CacheTest.php
- tests/Mpdf/ConfigurationTest.php
- tests/Mpdf/QrCode/QrCodeColorTest.php
- tests/Mpdf/TocNumbering.php
This will help us with better error messages when debugging errors.
> Use dedicated PHPUnit assertions

- src/RemoteContentFetcher.php
This makes it easier to debug problems with external resources
> Log socket error when it occurs

- src/Config/ConfigVariables.php
- src/Image/ImageProcessor.php
- src/Mpdf.php
- tests/Mpdf/Image/ImageProcessorTest.php
> Allow image stream whitelist to be customised

- src/Tag/BlockTag.php
- tests/Issues/Issue1003Test.php
> Fix PHP notice due to `auto` on padding_left / padding_right parameter

- src/Mpdf.php
- tests/Issues/Issue1134Test.php
[Issue 1134](https://github.com/mpdf/mpdf/issues/1134)
> Fix 1134 issue

- CHANGELOG.md
- src/Conversion/DecToOther.php
- src/Mpdf.php
- tests/Issues/Issue1201Test.php
Myanmar Language Support for Page Number.
> Page number Myanmar language support

- CHANGELOG.md
- src/Config/ConfigVariables.php
- src/Mpdf.php
- src/RemoteContentFetcher.php
Ability to customize User-Agent header in the HTTP requests sent by cURL fetching a content on remote server.
This allows the owners of the remote server to customize the response.
> ability to customize User-Agent header in the HTTP requests sent by cURL

- tests/Mpdf/Image/ImageProcessorTest.php
See https://github.com/mpdf/mpdf/issues/1263#issuecomment-662346871
> Resolve unit test mock error

- src/Shaper/Indic.php
> Fixed typo in message

- CHANGELOG.md
- src/Mpdf.php
- tests/Issues/Issue1320Test.php
Fixes issue 1320: First header of named page is added twice
> Fixes issue 1320: First header of named page is added twice

- CHANGELOG.md
- src/Barcode.php
- src/Barcode/Codabar.php
- src/Barcode/Code11.php
- src/Barcode/Code128.php
- src/Barcode/Code39.php
- src/Barcode/Code93.php
- src/Barcode/I25.php
- src/Barcode/Msi.php
- src/Barcode/S25.php
- src/Mpdf.php
- src/Tag/BarCode.php
- tests/Issues/Issue1430Test.php
Adds the functionality requested into #1430.
All existing tests passed
> Barcode quiet zones customization

- src/Mpdf.php
See https://github.com/mpdf/mpdf/issues/1447
> fixed file handle leak using Setssign's FpdiTrait::cleanUp()

- src/Mpdf.php
- tests/Issues/Issue1765Test.php
This should work as in versions of php prior 8
> Fix undefined array key at _tableGetMaxRowHeight

- src/Mpdf.php
- tests/Issues/Issue1170Test.php
> Fix footer links in PDF with different orientation pages

- CHANGELOG.md
- src/Writer/MetadataWriter.php
- tests/Issues/Issue2090Test.php
> Escape XML predefined entities
